"""Write assets/media/manifest.js from the files present and seedance/clips.json.

For each space the site prefers local optimised files (webm/mp4 + jpg still)
and falls back to the original Seedance render URL recorded in clips.json.
"""
import json
import os
import sys

root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
media = os.path.join(root, "assets", "media")
clips_path = os.path.join(root, "seedance", "clips.json")
clips = {}
if os.path.exists(clips_path):
    with open(clips_path, encoding="utf-8") as f:
        clips = json.load(f).get("clips", {})

entries = {}
for space in ["cafe", "salon", "nail", "office", "restaurant"]:
    formats = [ext for ext in ("webm", "mp4") if os.path.exists(os.path.join(media, f"{space}.{ext}"))]
    still = os.path.exists(os.path.join(media, f"{space}.jpg"))
    url = clips.get(space, {}).get("url")
    if formats or still or url:
        entry = {"video": formats, "still": still}
        if url:
            entry["url"] = url
        entries[space] = entry

with open(os.path.join(media, "manifest.js"), "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/write-manifest.py; lists the Seedance 2.0 media available.\n")
    f.write("window.PLOTO_MEDIA = " + json.dumps(entries, indent=2) + ";\n")
print(f"wrote assets/media/manifest.js ({len(entries)} spaces)", file=sys.stderr)
